// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Message {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class MessageChat;
class MessageData;
class MessageDataList;
class MessageRequest;
class MessageRequestRange;

// ===================================================================

class MessageChat : public ::google::protobuf::Message {
 public:
  MessageChat();
  virtual ~MessageChat();

  MessageChat(const MessageChat& from);

  inline MessageChat& operator=(const MessageChat& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageChat& default_instance();

  void Swap(MessageChat* other);

  // implements Message ----------------------------------------------

  inline MessageChat* New() const { return New(NULL); }

  MessageChat* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageChat& from);
  void MergeFrom(const MessageChat& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageChat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes data = 1;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // optional uint64 receiver = 2;
  void clear_receiver();
  static const int kReceiverFieldNumber = 2;
  ::google::protobuf::uint64 receiver() const;
  void set_receiver(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Message.MessageChat)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::uint64 receiver_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static MessageChat* default_instance_;
};
// -------------------------------------------------------------------

class MessageRequestRange : public ::google::protobuf::Message {
 public:
  MessageRequestRange();
  virtual ~MessageRequestRange();

  MessageRequestRange(const MessageRequestRange& from);

  inline MessageRequestRange& operator=(const MessageRequestRange& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageRequestRange& default_instance();

  void Swap(MessageRequestRange* other);

  // implements Message ----------------------------------------------

  inline MessageRequestRange* New() const { return New(NULL); }

  MessageRequestRange* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageRequestRange& from);
  void MergeFrom(const MessageRequestRange& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageRequestRange* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 start = 1;
  void clear_start();
  static const int kStartFieldNumber = 1;
  ::google::protobuf::int64 start() const;
  void set_start(::google::protobuf::int64 value);

  // optional int64 end = 2;
  void clear_end();
  static const int kEndFieldNumber = 2;
  ::google::protobuf::int64 end() const;
  void set_end(::google::protobuf::int64 value);

  // optional int32 length = 3;
  void clear_length();
  static const int kLengthFieldNumber = 3;
  ::google::protobuf::int32 length() const;
  void set_length(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.MessageRequestRange)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 start_;
  ::google::protobuf::int64 end_;
  ::google::protobuf::int32 length_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static MessageRequestRange* default_instance_;
};
// -------------------------------------------------------------------

class MessageRequest : public ::google::protobuf::Message {
 public:
  MessageRequest();
  virtual ~MessageRequest();

  MessageRequest(const MessageRequest& from);

  inline MessageRequest& operator=(const MessageRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageRequest& default_instance();

  void Swap(MessageRequest* other);

  // implements Message ----------------------------------------------

  inline MessageRequest* New() const { return New(NULL); }

  MessageRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageRequest& from);
  void MergeFrom(const MessageRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 class = 1;
  void clear_class_();
  static const int kClassFieldNumber = 1;
  ::google::protobuf::uint32 class_() const;
  void set_class_(::google::protobuf::uint32 value);

  // optional uint64 friend = 2;
  void clear_friend_();
  static const int kFriendFieldNumber = 2;
  ::google::protobuf::uint64 friend_() const;
  void set_friend_(::google::protobuf::uint64 value);

  // optional uint32 passage = 3;
  void clear_passage();
  static const int kPassageFieldNumber = 3;
  ::google::protobuf::uint32 passage() const;
  void set_passage(::google::protobuf::uint32 value);

  // repeated int64 index = 4;
  int index_size() const;
  void clear_index();
  static const int kIndexFieldNumber = 4;
  ::google::protobuf::int64 index(int index) const;
  void set_index(int index, ::google::protobuf::int64 value);
  void add_index(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      index() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_index();

  // repeated .Message.MessageRequestRange index_range = 5;
  int index_range_size() const;
  void clear_index_range();
  static const int kIndexRangeFieldNumber = 5;
  const ::Message::MessageRequestRange& index_range(int index) const;
  ::Message::MessageRequestRange* mutable_index_range(int index);
  ::Message::MessageRequestRange* add_index_range();
  ::google::protobuf::RepeatedPtrField< ::Message::MessageRequestRange >*
      mutable_index_range();
  const ::google::protobuf::RepeatedPtrField< ::Message::MessageRequestRange >&
      index_range() const;

  // @@protoc_insertion_point(class_scope:Message.MessageRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 friend__;
  ::google::protobuf::uint32 class__;
  ::google::protobuf::uint32 passage_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > index_;
  mutable int _index_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::Message::MessageRequestRange > index_range_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static MessageRequest* default_instance_;
};
// -------------------------------------------------------------------

class MessageData : public ::google::protobuf::Message {
 public:
  MessageData();
  virtual ~MessageData();

  MessageData(const MessageData& from);

  inline MessageData& operator=(const MessageData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageData& default_instance();

  void Swap(MessageData* other);

  // implements Message ----------------------------------------------

  inline MessageData* New() const { return New(NULL); }

  MessageData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageData& from);
  void MergeFrom(const MessageData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 index = 1;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::int64 index() const;
  void set_index(::google::protobuf::int64 value);

  // optional int64 real_index = 2;
  void clear_real_index();
  static const int kRealIndexFieldNumber = 2;
  ::google::protobuf::int64 real_index() const;
  void set_real_index(::google::protobuf::int64 value);

  // optional int64 time = 3;
  void clear_time();
  static const int kTimeFieldNumber = 3;
  ::google::protobuf::int64 time() const;
  void set_time(::google::protobuf::int64 value);

  // optional uint32 class = 4;
  void clear_class_();
  static const int kClassFieldNumber = 4;
  ::google::protobuf::uint32 class_() const;
  void set_class_(::google::protobuf::uint32 value);

  // optional uint32 type = 5;
  void clear_type();
  static const int kTypeFieldNumber = 5;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // optional uint64 sender = 6;
  void clear_sender();
  static const int kSenderFieldNumber = 6;
  ::google::protobuf::uint64 sender() const;
  void set_sender(::google::protobuf::uint64 value);

  // optional uint64 receiver = 7;
  void clear_receiver();
  static const int kReceiverFieldNumber = 7;
  ::google::protobuf::uint64 receiver() const;
  void set_receiver(::google::protobuf::uint64 value);

  // optional uint64 friend = 8;
  void clear_friend_();
  static const int kFriendFieldNumber = 8;
  ::google::protobuf::uint64 friend_() const;
  void set_friend_(::google::protobuf::uint64 value);

  // optional int64 master_index = 9;
  void clear_master_index();
  static const int kMasterIndexFieldNumber = 9;
  ::google::protobuf::int64 master_index() const;
  void set_master_index(::google::protobuf::int64 value);

  // optional bytes data_1 = 10;
  void clear_data_1();
  static const int kData1FieldNumber = 10;
  const ::std::string& data_1() const;
  void set_data_1(const ::std::string& value);
  void set_data_1(const char* value);
  void set_data_1(const void* value, size_t size);
  ::std::string* mutable_data_1();
  ::std::string* release_data_1();
  void set_allocated_data_1(::std::string* data_1);

  // optional bytes data_2 = 11;
  void clear_data_2();
  static const int kData2FieldNumber = 11;
  const ::std::string& data_2() const;
  void set_data_2(const ::std::string& value);
  void set_data_2(const char* value);
  void set_data_2(const void* value, size_t size);
  ::std::string* mutable_data_2();
  ::std::string* release_data_2();
  void set_allocated_data_2(::std::string* data_2);

  // optional bytes data_3 = 12;
  void clear_data_3();
  static const int kData3FieldNumber = 12;
  const ::std::string& data_3() const;
  void set_data_3(const ::std::string& value);
  void set_data_3(const char* value);
  void set_data_3(const void* value, size_t size);
  ::std::string* mutable_data_3();
  ::std::string* release_data_3();
  void set_allocated_data_3(::std::string* data_3);

  // optional bytes data_4 = 13;
  void clear_data_4();
  static const int kData4FieldNumber = 13;
  const ::std::string& data_4() const;
  void set_data_4(const ::std::string& value);
  void set_data_4(const char* value);
  void set_data_4(const void* value, size_t size);
  ::std::string* mutable_data_4();
  ::std::string* release_data_4();
  void set_allocated_data_4(::std::string* data_4);

  // @@protoc_insertion_point(class_scope:Message.MessageData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 index_;
  ::google::protobuf::int64 real_index_;
  ::google::protobuf::int64 time_;
  ::google::protobuf::uint32 class__;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint64 sender_;
  ::google::protobuf::uint64 receiver_;
  ::google::protobuf::uint64 friend__;
  ::google::protobuf::int64 master_index_;
  ::google::protobuf::internal::ArenaStringPtr data_1_;
  ::google::protobuf::internal::ArenaStringPtr data_2_;
  ::google::protobuf::internal::ArenaStringPtr data_3_;
  ::google::protobuf::internal::ArenaStringPtr data_4_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static MessageData* default_instance_;
};
// -------------------------------------------------------------------

class MessageDataList : public ::google::protobuf::Message {
 public:
  MessageDataList();
  virtual ~MessageDataList();

  MessageDataList(const MessageDataList& from);

  inline MessageDataList& operator=(const MessageDataList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageDataList& default_instance();

  void Swap(MessageDataList* other);

  // implements Message ----------------------------------------------

  inline MessageDataList* New() const { return New(NULL); }

  MessageDataList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageDataList& from);
  void MergeFrom(const MessageDataList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageDataList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Message.MessageData data = 1;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::Message::MessageData& data(int index) const;
  ::Message::MessageData* mutable_data(int index);
  ::Message::MessageData* add_data();
  ::google::protobuf::RepeatedPtrField< ::Message::MessageData >*
      mutable_data();
  const ::google::protobuf::RepeatedPtrField< ::Message::MessageData >&
      data() const;

  // @@protoc_insertion_point(class_scope:Message.MessageDataList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::Message::MessageData > data_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static MessageDataList* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageChat

// optional bytes data = 1;
inline void MessageChat::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MessageChat::data() const {
  // @@protoc_insertion_point(field_get:Message.MessageChat.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageChat::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Message.MessageChat.data)
}
inline void MessageChat::set_data(const char* value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.MessageChat.data)
}
inline void MessageChat::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.MessageChat.data)
}
inline ::std::string* MessageChat::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:Message.MessageChat.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageChat::release_data() {
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageChat::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:Message.MessageChat.data)
}

// optional uint64 receiver = 2;
inline void MessageChat::clear_receiver() {
  receiver_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MessageChat::receiver() const {
  // @@protoc_insertion_point(field_get:Message.MessageChat.receiver)
  return receiver_;
}
inline void MessageChat::set_receiver(::google::protobuf::uint64 value) {
  
  receiver_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageChat.receiver)
}

// -------------------------------------------------------------------

// MessageRequestRange

// optional int64 start = 1;
inline void MessageRequestRange::clear_start() {
  start_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MessageRequestRange::start() const {
  // @@protoc_insertion_point(field_get:Message.MessageRequestRange.start)
  return start_;
}
inline void MessageRequestRange::set_start(::google::protobuf::int64 value) {
  
  start_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageRequestRange.start)
}

// optional int64 end = 2;
inline void MessageRequestRange::clear_end() {
  end_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MessageRequestRange::end() const {
  // @@protoc_insertion_point(field_get:Message.MessageRequestRange.end)
  return end_;
}
inline void MessageRequestRange::set_end(::google::protobuf::int64 value) {
  
  end_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageRequestRange.end)
}

// optional int32 length = 3;
inline void MessageRequestRange::clear_length() {
  length_ = 0;
}
inline ::google::protobuf::int32 MessageRequestRange::length() const {
  // @@protoc_insertion_point(field_get:Message.MessageRequestRange.length)
  return length_;
}
inline void MessageRequestRange::set_length(::google::protobuf::int32 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageRequestRange.length)
}

// -------------------------------------------------------------------

// MessageRequest

// optional uint32 class = 1;
inline void MessageRequest::clear_class_() {
  class__ = 0u;
}
inline ::google::protobuf::uint32 MessageRequest::class_() const {
  // @@protoc_insertion_point(field_get:Message.MessageRequest.class)
  return class__;
}
inline void MessageRequest::set_class_(::google::protobuf::uint32 value) {
  
  class__ = value;
  // @@protoc_insertion_point(field_set:Message.MessageRequest.class)
}

// optional uint64 friend = 2;
inline void MessageRequest::clear_friend_() {
  friend__ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MessageRequest::friend_() const {
  // @@protoc_insertion_point(field_get:Message.MessageRequest.friend)
  return friend__;
}
inline void MessageRequest::set_friend_(::google::protobuf::uint64 value) {
  
  friend__ = value;
  // @@protoc_insertion_point(field_set:Message.MessageRequest.friend)
}

// optional uint32 passage = 3;
inline void MessageRequest::clear_passage() {
  passage_ = 0u;
}
inline ::google::protobuf::uint32 MessageRequest::passage() const {
  // @@protoc_insertion_point(field_get:Message.MessageRequest.passage)
  return passage_;
}
inline void MessageRequest::set_passage(::google::protobuf::uint32 value) {
  
  passage_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageRequest.passage)
}

// repeated int64 index = 4;
inline int MessageRequest::index_size() const {
  return index_.size();
}
inline void MessageRequest::clear_index() {
  index_.Clear();
}
inline ::google::protobuf::int64 MessageRequest::index(int index) const {
  // @@protoc_insertion_point(field_get:Message.MessageRequest.index)
  return index_.Get(index);
}
inline void MessageRequest::set_index(int index, ::google::protobuf::int64 value) {
  index_.Set(index, value);
  // @@protoc_insertion_point(field_set:Message.MessageRequest.index)
}
inline void MessageRequest::add_index(::google::protobuf::int64 value) {
  index_.Add(value);
  // @@protoc_insertion_point(field_add:Message.MessageRequest.index)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
MessageRequest::index() const {
  // @@protoc_insertion_point(field_list:Message.MessageRequest.index)
  return index_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
MessageRequest::mutable_index() {
  // @@protoc_insertion_point(field_mutable_list:Message.MessageRequest.index)
  return &index_;
}

// repeated .Message.MessageRequestRange index_range = 5;
inline int MessageRequest::index_range_size() const {
  return index_range_.size();
}
inline void MessageRequest::clear_index_range() {
  index_range_.Clear();
}
inline const ::Message::MessageRequestRange& MessageRequest::index_range(int index) const {
  // @@protoc_insertion_point(field_get:Message.MessageRequest.index_range)
  return index_range_.Get(index);
}
inline ::Message::MessageRequestRange* MessageRequest::mutable_index_range(int index) {
  // @@protoc_insertion_point(field_mutable:Message.MessageRequest.index_range)
  return index_range_.Mutable(index);
}
inline ::Message::MessageRequestRange* MessageRequest::add_index_range() {
  // @@protoc_insertion_point(field_add:Message.MessageRequest.index_range)
  return index_range_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Message::MessageRequestRange >*
MessageRequest::mutable_index_range() {
  // @@protoc_insertion_point(field_mutable_list:Message.MessageRequest.index_range)
  return &index_range_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Message::MessageRequestRange >&
MessageRequest::index_range() const {
  // @@protoc_insertion_point(field_list:Message.MessageRequest.index_range)
  return index_range_;
}

// -------------------------------------------------------------------

// MessageData

// optional int64 index = 1;
inline void MessageData::clear_index() {
  index_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MessageData::index() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.index)
  return index_;
}
inline void MessageData::set_index(::google::protobuf::int64 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageData.index)
}

// optional int64 real_index = 2;
inline void MessageData::clear_real_index() {
  real_index_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MessageData::real_index() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.real_index)
  return real_index_;
}
inline void MessageData::set_real_index(::google::protobuf::int64 value) {
  
  real_index_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageData.real_index)
}

// optional int64 time = 3;
inline void MessageData::clear_time() {
  time_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MessageData::time() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.time)
  return time_;
}
inline void MessageData::set_time(::google::protobuf::int64 value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageData.time)
}

// optional uint32 class = 4;
inline void MessageData::clear_class_() {
  class__ = 0u;
}
inline ::google::protobuf::uint32 MessageData::class_() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.class)
  return class__;
}
inline void MessageData::set_class_(::google::protobuf::uint32 value) {
  
  class__ = value;
  // @@protoc_insertion_point(field_set:Message.MessageData.class)
}

// optional uint32 type = 5;
inline void MessageData::clear_type() {
  type_ = 0u;
}
inline ::google::protobuf::uint32 MessageData::type() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.type)
  return type_;
}
inline void MessageData::set_type(::google::protobuf::uint32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageData.type)
}

// optional uint64 sender = 6;
inline void MessageData::clear_sender() {
  sender_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MessageData::sender() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.sender)
  return sender_;
}
inline void MessageData::set_sender(::google::protobuf::uint64 value) {
  
  sender_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageData.sender)
}

// optional uint64 receiver = 7;
inline void MessageData::clear_receiver() {
  receiver_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MessageData::receiver() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.receiver)
  return receiver_;
}
inline void MessageData::set_receiver(::google::protobuf::uint64 value) {
  
  receiver_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageData.receiver)
}

// optional uint64 friend = 8;
inline void MessageData::clear_friend_() {
  friend__ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MessageData::friend_() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.friend)
  return friend__;
}
inline void MessageData::set_friend_(::google::protobuf::uint64 value) {
  
  friend__ = value;
  // @@protoc_insertion_point(field_set:Message.MessageData.friend)
}

// optional int64 master_index = 9;
inline void MessageData::clear_master_index() {
  master_index_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MessageData::master_index() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.master_index)
  return master_index_;
}
inline void MessageData::set_master_index(::google::protobuf::int64 value) {
  
  master_index_ = value;
  // @@protoc_insertion_point(field_set:Message.MessageData.master_index)
}

// optional bytes data_1 = 10;
inline void MessageData::clear_data_1() {
  data_1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MessageData::data_1() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.data_1)
  return data_1_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageData::set_data_1(const ::std::string& value) {
  
  data_1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Message.MessageData.data_1)
}
inline void MessageData::set_data_1(const char* value) {
  
  data_1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.MessageData.data_1)
}
inline void MessageData::set_data_1(const void* value, size_t size) {
  
  data_1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.MessageData.data_1)
}
inline ::std::string* MessageData::mutable_data_1() {
  
  // @@protoc_insertion_point(field_mutable:Message.MessageData.data_1)
  return data_1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageData::release_data_1() {
  
  return data_1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageData::set_allocated_data_1(::std::string* data_1) {
  if (data_1 != NULL) {
    
  } else {
    
  }
  data_1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data_1);
  // @@protoc_insertion_point(field_set_allocated:Message.MessageData.data_1)
}

// optional bytes data_2 = 11;
inline void MessageData::clear_data_2() {
  data_2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MessageData::data_2() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.data_2)
  return data_2_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageData::set_data_2(const ::std::string& value) {
  
  data_2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Message.MessageData.data_2)
}
inline void MessageData::set_data_2(const char* value) {
  
  data_2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.MessageData.data_2)
}
inline void MessageData::set_data_2(const void* value, size_t size) {
  
  data_2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.MessageData.data_2)
}
inline ::std::string* MessageData::mutable_data_2() {
  
  // @@protoc_insertion_point(field_mutable:Message.MessageData.data_2)
  return data_2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageData::release_data_2() {
  
  return data_2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageData::set_allocated_data_2(::std::string* data_2) {
  if (data_2 != NULL) {
    
  } else {
    
  }
  data_2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data_2);
  // @@protoc_insertion_point(field_set_allocated:Message.MessageData.data_2)
}

// optional bytes data_3 = 12;
inline void MessageData::clear_data_3() {
  data_3_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MessageData::data_3() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.data_3)
  return data_3_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageData::set_data_3(const ::std::string& value) {
  
  data_3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Message.MessageData.data_3)
}
inline void MessageData::set_data_3(const char* value) {
  
  data_3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.MessageData.data_3)
}
inline void MessageData::set_data_3(const void* value, size_t size) {
  
  data_3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.MessageData.data_3)
}
inline ::std::string* MessageData::mutable_data_3() {
  
  // @@protoc_insertion_point(field_mutable:Message.MessageData.data_3)
  return data_3_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageData::release_data_3() {
  
  return data_3_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageData::set_allocated_data_3(::std::string* data_3) {
  if (data_3 != NULL) {
    
  } else {
    
  }
  data_3_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data_3);
  // @@protoc_insertion_point(field_set_allocated:Message.MessageData.data_3)
}

// optional bytes data_4 = 13;
inline void MessageData::clear_data_4() {
  data_4_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MessageData::data_4() const {
  // @@protoc_insertion_point(field_get:Message.MessageData.data_4)
  return data_4_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageData::set_data_4(const ::std::string& value) {
  
  data_4_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Message.MessageData.data_4)
}
inline void MessageData::set_data_4(const char* value) {
  
  data_4_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.MessageData.data_4)
}
inline void MessageData::set_data_4(const void* value, size_t size) {
  
  data_4_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.MessageData.data_4)
}
inline ::std::string* MessageData::mutable_data_4() {
  
  // @@protoc_insertion_point(field_mutable:Message.MessageData.data_4)
  return data_4_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageData::release_data_4() {
  
  return data_4_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageData::set_allocated_data_4(::std::string* data_4) {
  if (data_4 != NULL) {
    
  } else {
    
  }
  data_4_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data_4);
  // @@protoc_insertion_point(field_set_allocated:Message.MessageData.data_4)
}

// -------------------------------------------------------------------

// MessageDataList

// repeated .Message.MessageData data = 1;
inline int MessageDataList::data_size() const {
  return data_.size();
}
inline void MessageDataList::clear_data() {
  data_.Clear();
}
inline const ::Message::MessageData& MessageDataList::data(int index) const {
  // @@protoc_insertion_point(field_get:Message.MessageDataList.data)
  return data_.Get(index);
}
inline ::Message::MessageData* MessageDataList::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:Message.MessageDataList.data)
  return data_.Mutable(index);
}
inline ::Message::MessageData* MessageDataList::add_data() {
  // @@protoc_insertion_point(field_add:Message.MessageDataList.data)
  return data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Message::MessageData >*
MessageDataList::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:Message.MessageDataList.data)
  return &data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Message::MessageData >&
MessageDataList::data() const {
  // @@protoc_insertion_point(field_list:Message.MessageDataList.data)
  return data_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
